### ISSUE TITLE
Failure during 'make test'

### ISSUE THREAD

**Issue by jkeenan** [genehack/Git-Wrapper#41]
```
  CPAN.pm: Building G/GE/GENEHACK/Git-Wrapper-0.030.tar.gz

Checking if your kit is complete...
Looks good
Writing Makefile for Git::Wrapper
Writing MYMETA.yml and MYMETA.json
cp lib/Git/Wrapper/File/RawModification.pm blib/lib/Git/Wrapper/File/RawModification.pm
cp lib/Git/Wrapper.pm blib/lib/Git/Wrapper.pm
cp lib/Git/Wrapper/Statuses.pm blib/lib/Git/Wrapper/Statuses.pm
cp lib/Git/Wrapper/Log.pm blib/lib/Git/Wrapper/Log.pm
cp lib/Git/Wrapper/Exception.pm blib/lib/Git/Wrapper/Exception.pm
cp lib/Git/Wrapper/Status.pm blib/lib/Git/Wrapper/Status.pm
Manifying blib/man3/Git::Wrapper::Exception.3
Manifying blib/man3/Git::Wrapper::Log.3
Manifying blib/man3/Git::Wrapper.3
Manifying blib/man3/Git::Wrapper::File::RawModification.3
Manifying blib/man3/Git::Wrapper::Statuses.3
Manifying blib/man3/Git::Wrapper::Status.3
  GENEHACK/Git-Wrapper-0.030.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 /usr/local/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ................ 6/6 # Testing Git::Wrapper 0.030
t/00-load.t ................ ok   
t/000-requires_external.t .. ok   
t/author-err.t ............. skipped: these tests are for testing by the author
t/basic.t .................. # Testing git version: 1.6.3.2
t/basic.t .................. ok    
t/git_binary.t ............. ok   
t/parse_args.t ............. ok    
t/path_class.t ............. # Testing git version: 1.6.3.2
t/path_class.t ............. 2/? fatal: '/tmp/FRA4lgN3mK/baz' is outside repository
# Tests were run but no plan was declared and done_testing() was not seen.
t/path_class.t ............. Dubious, test returned 128 (wstat 32768, 0x8000)
All 2 subtests passed 
t/release-pod-coverage.t ... skipped: these tests are for release candidate testing
t/release-pod-syntax.t ..... skipped: these tests are for release candidate testing

Test Summary Report
-------------------
t/path_class.t           (Wstat: 32768 Tests: 2 Failed: 0)
  Non-zero exit status: 128
  Parse errors: No plan found in TAP output
Files=9, Tests=62, 21 wallclock secs ( 0.24 usr  0.14 sys +  3.21 cusr  2.91 csys =  6.50 CPU)
Result: FAIL
Failed 1/9 test programs. 0/62 subtests failed.
make: *** [test_dynamic] Error 255
  GENEHACK/Git-Wrapper-0.030.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports GENEHACK/Git-Wrapper-0.030.tar.gz
Running make install
  make test had returned bad status, won't install without force
Failed during this command:
 GENEHACK/Git-Wrapper-0.030.tar.gz            : make_test NO
install
```
```
$ perl -V
Summary of my perl5 (revision 5 version 18 subversion 0) configuration:
   
  Platform:
    osname=darwin, osvers=8.11.0, archname=darwin-2level
    uname='darwin macintosh-9.local 8.11.0 darwin kernel version 8.11.0: wed oct 10 18:26:00 pdt 2007; root:xnu-792.24.17~1release_ppc power macintosh powerpc '
    config_args='-des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -I/usr/local/include -I/opt/local/include',
    optimize='-O3',
    cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -I/usr/local/include -I/opt/local/include'
    ccversion='', gccversion='4.0.1 (Apple Computer, Inc. build 5250)', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=4321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -L/usr/local/lib -L/opt/local/lib'
    libpth=/usr/local/lib /opt/local/lib /usr/lib
    libs=-ldbm -ldl -lm -lc
    perllibs=-ldl -lm -lc
    libc=, so=dylib, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib'


Characteristics of this binary (from libperl): 
  Compile-time options: HAS_TIMES PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV PERL_SAWAMPERSAND USE_LARGE_FILES
                        USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
  Built under darwin
  Compiled at May 18 2013 12:31:26
  %ENV:
    PERLBREW_BASHRC_VERSION="0.59"
    PERLBREW_HOME="/Users/jimk/.perlbrew"
    PERLBREW_MANPATH=""
    PERLBREW_PATH="/Users/jimk/perl5/perlbrew/bin"
    PERLBREW_ROOT="/Users/jimk/perl5/perlbrew"
    PERLBREW_VERSION="0.59"
  @INC:
    /usr/local/lib/perl5/site_perl/5.18.0/darwin-2level
    /usr/local/lib/perl5/site_perl/5.18.0
    /usr/local/lib/perl5/5.18.0/darwin-2level
    /usr/local/lib/perl5/5.18.0
    /usr/local/lib/perl5/site_perl/5.16.0
    /usr/local/lib/perl5/site_perl/5.14.2
    /usr/local/lib/perl5/site_perl/5.14.0
    /usr/local/lib/perl5/site_perl/5.12.0
    /usr/local/lib/perl5/site_perl/5.10.1
    /usr/local/lib/perl5/site_perl/5.10.0
    /usr/local/lib/perl5/site_perl/5.8.6
    /usr/local/lib/perl5/site_perl
    .
```

**Comment by estrabd** [comment]
@jkeenan, I am trying to reproduce this report as part of the pr-challenge, and I can't.  Can you provide me with any details that might allow me to do so? Thank you

    perl -V
    Summary of my perl5 (revision 5 version 18 subversion 0) configuration:

      Platform:
        osname=darwin, osvers=13.4.0, archname=darwin-2level
        uname='darwin b-estrade.local 13.4.0 darwin kernel version 13.4.0: sun aug 17 19:50:11 pdt 2014; root:xnu-2422.115.4~1release_x86_64 x86_64 '
        config_args='-de -Dprefix=/Users/brett/perl5/perlbrew/perls/perl-5.18.0 -Aeval:scriptdir=/Users/brett/perl5/perlbrew/perls/perl-5.18.0/bin'
        hint=recommended, useposix=true, d_sigaction=define
        useithreads=undef, usemultiplicity=undef
        useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
        use64bitint=define, use64bitall=define, uselongdouble=undef
        usemymalloc=n, bincompat5005=undef
      Compiler:
        cc='cc', ccflags ='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include',
        optimize='-O3',
        cppflags='-fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
        ccversion='', gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)', gccosandvers=''
        intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
        d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
        ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
        alignbytes=8, prototype=define
      Linker and Libraries:
        ld='env MACOSX_DEPLOYMENT_TARGET=10.3 cc', ldflags =' -fstack-protector -L/usr/local/lib'
        libpth=/usr/local/lib /usr/lib
        libs=-ldbm -ldl -lm -lutil -lc
        perllibs=-ldl -lm -lutil -lc
        libc=, so=dylib, useshrplib=false, libperl=libperl.a
        gnulibc_version=''
      Dynamic Linking:
        dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
        cccdlflags=' ', lddlflags=' -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector'


    Characteristics of this binary (from libperl):
      Compile-time options: HAS_TIMES PERLIO_LAYERS PERL_DONT_CREATE_GVSV
                            PERL_HASH_FUNC_ONE_AT_A_TIME_HARD PERL_MALLOC_WRAP
                            PERL_PRESERVE_IVUV PERL_SAWAMPERSAND USE_64_BIT_ALL
                            USE_64_BIT_INT USE_LARGE_FILES USE_LOCALE
                            USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                            USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
      Locally applied patches:
            Devel::PatchPerl 1.30
      Built under darwin
      Compiled at Jan  2 2015 22:33:27

**Comment by jkeenan** [comment]
Yes, I am still getting this test failure.  Note that this machine is more than 10 years old, is therefore running an old version of Mac OS X and is unable to install more modern versions of git (at least, via installation of a binary) than 1.6.3.2.  I am, however, still able to install Perl from source and install the latest versions of CPAN distributions which, unlike this one, do not have outside dependencies.  And since I do not get these errors on a newer machine running git version 1.9.1, the problem may be in that older git and not in any Perl code.

That being said, it is surprising that Git::Wrapper fails its tests once Path::Class::Dir and Path::Class::File enter the picture.  Below I am pasting (a) a version of t/path_class.t hacked up with debugging output; and (b) the output of 'prove -vb t/path_class.t > somefile 2>&1'.  Note that the test gets almost all of the way through before failing:  I reach debugging line KKK but not LLL.

```perl
use strict;
use warnings;
use Test::More;

use File::Temp qw(tempdir);
use Git::Wrapper;
use POSIX qw(strftime);
use Sort::Versions;
use Test::Deep;
use Test::Exception;

eval "use Path::Class 0.26; 1" or plan skip_all =>
    "Path::Class 0.26 is required for this test.";

my $tempdir = tempdir(CLEANUP => 1);
say STDERR "AAA: tempdir:                     $tempdir";

my $dir = Path::Class::dir($tempdir);
say STDERR "BBB: \$dir (via Path::Class::dir): $dir";

my $git = Git::Wrapper->new($dir);
say STDERR "CCC: Created Git::Wrapper object";

my $version = $git->version;
if ( versioncmp( $git->version , '1.5.0') eq -1 ) {
  plan skip_all =>
    "Git prior to v1.5.0 doesn't support 'config' subcmd which we need for this test."
}

diag( "Testing git version: " . $version );

$git->init; # 'git init' also added in v1.5.0 so we are safe
say STDERR "DDD: Performed git->init";

$git->config( 'user.name'  , 'Test User'        );
$git->config( 'user.email' , 'test@example.com' );
say STDERR "EEE: Performed git->config twice";

# make sure git isnt munging our content so we have consistent hashes
$git->config( 'core.autocrlf' , 'false' );
$git->config( 'core.safecrlf' , 'false' );
say STDERR "FFF: Performed git->config twice more";

my $foo = $dir->subdir('foo');
$foo->mkpath;
say STDERR "GGG: Able to call Path::Class 'subdir' and 'mkpath' methods";

$foo->file('bar')->spew(iomode => '>:raw', "hello\n");
say STDERR "GGG: Able to call Path::Class 'file->spew'";

is_deeply(
  [ $git->ls_files({ o => 1 }) ],
  [ 'foo/bar' ],
  "Got expected result of \$git->ls_files with 'o'"
);

$git->add(Path::Class::dir('.'));
say STDERR "HHH: Able to call \$git->add on Path::Class::dir on .";
is_deeply(
  [ $git->ls_files ],
  [ 'foo/bar' ],
  "Got expected result of \$git->ls_files"
);

$git->commit({ message => "FIRST\n\n\tBODY\n" });
say STDERR "III: Able to call \$git->commit";

my $baz = $dir->file('baz');
say STDERR "JJJ: Able to call \$dir->file, which is a ", ref($baz), " object";

$baz->spew("world\n");
say STDERR "KKK: Able to call \$baz->spew";

$git->add($baz);
say STDERR "LLL: Able to call \$git->add on \$baz";

ok(1, "Made it this far!");

done_testing();
```

```shell
AAA: tempdir:                     /tmp/XH3q8RbNII
BBB: $dir (via Path::Class::dir): /tmp/XH3q8RbNII
CCC: Created Git::Wrapper object
# Testing git version: 1.6.3.2
DDD: Performed git->init
EEE: Performed git->config twice
FFF: Performed git->config twice more
GGG: Able to call Path::Class 'subdir' and 'mkpath' methods
GGG: Able to call Path::Class 'file->spew'
HHH: Able to call $git->add on Path::Class::dir on .
III: Able to call $git->commit
JJJ: Able to call $dir->file, which is a Path::Class::File object
KKK: Able to call $baz->spew
fatal: '/tmp/XH3q8RbNII/baz' is outside repository
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 128 just after 2.
t/path_class.t .. 
ok 1 - Got expected result of $git->ls_files with 'o'
ok 2 - Got expected result of $git->ls_files
Dubious, test returned 128 (wstat 32768, 0x8000)
All 2 subtests passed 

Test Summary Report
-------------------
t/path_class.t (Wstat: 32768 Tests: 2 Failed: 0)
  Non-zero exit status: 128
  Parse errors: No plan found in TAP output
Files=1, Tests=2,  1 wallclock secs ( 0.11 usr  0.03 sys +  0.45 cusr  0.42 csys =  1.01 CPU)
Result: FAIL
```

**Comment by estrabd** [comment]
Thank you, @jkeenan. I'll see what I can figure out.

**Comment by estrabd** [comment]
I was able to reproduce it by using the same version of git, 1.6.3.2,

https://github.com/git/git/releases/tag/v1.6.3.2

I'll start poking at it.

**Comment by estrabd** [comment]
Based on my testing of git versions, the first one in which the test starts working is 1.7.5. In versions 1.7.4 down through 1.6.3.2, it fails as you have observed.  I didn't test all versions, I did a binary search sort of thing.

In any case, give that we have possibly identified the lowest version of git for which the test doesn't fail, what is the proper course of action?

Thanks!

**Comment by jkeenan** [comment]
On 01/05/2015 06:23 PM, B. Estrade wrote:
>
> Based on my testing of git versions, the first one in which the test starts working is 1.7.5. In versions 1.7.4 down through 1.6.3.2, it fails as you have observed.  I didn't test all versions, I did a binary search sort of thing.
>
> In any case, give that we have possibly identified the lowest version of git for which the test doesn't fail, what is the proper course of action?
>

My congratulations to you on having the fortitude to install all these 
different git versions for testing!

This is genehack's call.  I'm only interested insofar as the current 
implementation of my CPAN distro Git-Reduce-Tests wraps around 
Git::Wrapper to get access to git commands in OO format.  I was trying 
to get Git-Reduce-Tests to pass all its tests on my (10-year-old) iBook 
G4 when I encountered this failure.  If I really wanted to, I could do a 
force-install of Git-Wrapper on that machine and have Git-Reduce-Tests 
do that.

IIRC, that test file already has one stipulation as to git minimum 
version in it.  Adding a requirement for 1.7.5 and documenting that in 
the POD might suffice.

Thank you very much.
Jim Keenan

**Comment by estrabd** [comment]
@genehack please let me know what you'd like me to do. I tested it on FreeBSD, and 1.7.4 seems to work fine on there. I am guessing the same for Linux, so it might be a weird OS X issue that is still not resolved for 1.7.4 and below.  Should I just document it as a potential "known issue"? 

T. Hanks,
Brett

**Comment by estrabd** [comment]
I went ahead and created the pull request that documents this compatibility issue on Mac OS X for git version 1.7.4 and below, https://github.com/genehack/Git-Wrapper/pull/56 - I am going to move on to some more functionality related issues.  Hopefully this will suffice.

**Comment by genehack** [comment]
I ended up fixing this in a different way (excluding the tests in the "known bad" situation). Thanks for pushing to get it cleared up.

**Comment by karenetheridge** [comment]
I wonder if anything jumped out from the git changes history that looked relevant to this problem?

**Comment by estrabd** [comment]
Ok, so long as my effort to find the earliest working git was worth, how you choose to use this information is up to you.
