### ISSUE TITLE
git log --format 

### ISSUE THREAD

**Issue by genehack** [genehack/Git-Wrapper#43]
See https://rt.cpan.org/Ticket/Display.html?id=64665 for gory details.

**Comment by estrabd** [comment]
I've been handed this module as part of the PR challenge, so I'll be taking a look at this as part of it.

**Comment by estrabd** [comment]
I read the RT ticket, and I can't reproduce the issue nor can I figure out exactly what the issue is. Has this been resolved?

**Comment by estrabd** [comment]
Hello, I've finally figured out what all of this is about. I am working on it.

**Comment by estrabd** [comment]
I am not yet ready to commit, but I have a preview of my changes at here - https://github.com/estrabd/Git-Wrapper/tree/Issue-43-handle-custom-log-format

My basic approach is as you suggested in RT, if --format is detected, don't try to parse. I went a step further and added G::W::Log::Custom.

My recommendation is also to not get into the business of parsing the output, so just return the entire output of the git log command using the custom format. If you see any show stoppers, let me know.

I am going to finalize the POD and make sure I am comfortable with the test coverage; but then I'll submit the pull request.

Feedback is welcome.

Thank you,
Brett

**Comment by estrabd** [comment]
I have issued the Pull Request https://github.com/genehack/Git-Wrapper/pull/57 that will hopefully address the issue adequately. Please provide feedback outlining any areas of concern and how to best rectify them. Thank you.

**Comment by estrabd** [comment]
Please consider PR https://github.com/genehack/Git-Wrapper/pull/65.
