### ISSUE TITLE
Fails to install on CentOS 6 w/o git config file

### ISSUE THREAD

**Issue by jmaslak** [genehack/Git-Wrapper#74]
Makefile.PL dies at line 14 when it runs git config --list on CentOS 6 and the user doesn't have a .gitconfig in their home directory directory.  It dies with a misleading error message about "git seems broken; maybe check your HOME environment variable?"

If you run git config --list from the command line, it returns a value of 128 and the error string "fatal: error processing config file(s)"  Git with CentOS 6.8 is 1.7.1 - and this appears to be an issue with this version of Git, but it would be nice to at least have a better error message when Git::Wrapper refuses to install.

**Comment by genehack** [comment]
How about "Unable to run `git config --list`. Do you need to add a ~/.gitconfig file?" for that error message, how's that grab you?

**Comment by jmaslak** [comment]
Yes, that would be perfect I think.

**Comment by genehack** [comment]
This will be in the next stable release; closing the issue out.
