### ISSUE TITLE
[PATCH] spelling fix

### ISSUE THREAD

**Issue by gregoa** [genehack/Git-Wrapper#75]
In Debian we are currently applying the following patch to
Git-Wrapper.
We thought you might be interested in it too.

    Description: spelling fix
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-08-19
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libgit-wrapper-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by genehack** [comment]
Thank you! I applied this patch manually in 222224c7b9b69d2a96bfcdfa24665755097dc746.
