### ISSUE TITLE
Test fails with tab/space issue

### ISSUE THREAD

**Issue by jplindstrom** [genehack/Git-Wrapper#79]
The tests fail during install with:

```
# Testing git version: 2.9.2
#   Failed test 'message'
#   at t/basic.t line 77.
#          got: 'FIRST
# 
#         BODY
# '
#     expected: 'FIRST
# 
# 	BODY
# '
# Looks like you failed 1 test of 26.
t/basic.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
```

Ubuntu 14.4, but I rather suspect the git version might be to blame. I checked some green CPAN testers output and it was using 1.8.3, e.g.
http://www.cpantesters.org/cpan/report/7f455f80-c654-11e4-b221-9e126cbd7f71

perl -v
This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux

git --version
git version 2.9.2

**Comment by genehack** [comment]
This is fixed in the most recent dev release, which will be released as stable later today. 

I'm going to go ahead and close this out; thanks for reporting.
