### ISSUE TITLE
Original source code for perl-git-wrapper.

### ISSUE THREAD

**Issue by mdeguzis** [genehack/Git-Wrapper#92]
Hi, sorry I was not able to find a better way to get in touch. I maintain the AUR package at https://aur.archlinux.org/packages/perl-git-wrapper for Arch Linux. I am using a tarball from cpan.org, but I am curious if this is the better "source of truth" for the source code, as I see there was a recent PR accepted.

Thank you.

**Comment by genehack** [comment]
No, the CPAN release is the official upstream for this module. Code in this repo that hasn't yet been released to CPAN hasn't been fully tested and vetted. 

Thanks.
