### ISSUE TITLE
[Question] How do you add non-hash parrameters?

### ISSUE THREAD

**Issue by xsawyerx** [genehack/Git-Wrapper#97]
I couldn't find this in the documentation, sorry.

How do I run something like this:

    git pull --rebase=preserve origin master

In this case, I can handle the rebase=preserve because it's key/value, but the other two parameters, which I tend to use when wanting to pull data from only one ref, I have no idea how to write.

**Comment by genehack** [comment]
This should do what you want: 

```
use Git::Wrapper
my $gw = Git::Wrapper->new('path/to/repo');
$gw->pull({ rebase => preserve }, 'origin', 'master' ); 
```

Note that if you flip `$Git::Wrapper::DEBUG` to 1 it will print out each command that it is going to run. Example from REPL:

```
1> use Git::Wrapper;
2> my $gw = Git::Wrapper->new('./');
$res[0] = bless( {
         'dir' => './'
       }, 'Git::Wrapper' )
3> $Git::Wrapper::DEBUG = 1;
$res[1] = 1
4> $gw->pull({ rebase => 'preserve' }, 'origin', 'master' );
git pull --rebase=preserve origin master
status: 0
$res[2] = [
  'Already up to date.',
' 'Rebasing (1/1)
]
```

**Comment by xsawyerx** [comment]
Cool, thanks!
